[package]
name = "terminal-echo"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
libc = "0.2.141"
mio = "0.8.6"
nix = "0.26.2"
terminal-common = { version = "0.1.0", path = "../terminal-common" }
